training_pipeline_config:
  pipeline: Income_pipeline
  artifact_dir: Artifact


data_ingestion_config:
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 


