
schema_config:
  schema_dir: config
  schema_file: schema.yaml



training_pipeline_config:
  pipeline: Income_pipeline
  artifact_dir: Artifact

data_ingestion_config:
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 

data_validation_config:
  data_validation: data_validation
  validation_dir: validated_data
  Train: train
  Test: test 

data_transformation_config:
  transformed_dir: transformed_data                # Directory
  transformed_train_dir: train                       # Train Directory
  transformed_test_dir: test                            # Test Directory
  preprocessing_dir: preprocesser                       # Preprocessor Directory
  feature_engineering_object_file_name: feat_eng.pkl        # feature eng file
  preprocessed_object_file_name: preprocessed.pkl           # preprocessor gile


model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
