File_Name: adult.csv

column_names:
  age: int
  workclass: object
  fnlwgt: int
  education: object
  educational-num: int
  marital-status: object
  occupation: object
  relationship: object
  race: object
  gender: object
  capital-gain: int
  capital-loss: int
  hours-per-week: int
  native-country: object
  income: object



drop_columns:


numerical Columns:
- age: Numerical
- fnlwgt: Numerical
- educational-num: Numerical
- capital-gain: Numerical
- capital-loss: Numerical
- hours-per-week: Numerical

categorical Columns:
- workclass: Categorical
- education: Categorical
- marital-status: Categorical
- occupation: Categorical
- relationship: Categorical
- race: Categorical
- gender: Categorical
- native-country: Categorical


one_hot_encoder_columns:
- workclass: Categorical
- education: Categorical
- marital-status: Categorical
- occupation: Categorical
- relationship: Categorical
- race: Categorical
- gender: Categorical
- native-country: Categorical



target_columns:
- income: Categorical

