File_Name: adult.csv

column_names:
  age: int64
  workclass: object
  fnlwgt: int64
  education: object
  marital-status: object
  occupation: object
  relationship: object
  educational-num: int64
  race: object
  gender: object
  capital-gain: int64
  capital-loss: int64
  hours-per-week: int64
  native-country: object
  income: object



drop_columns:
  - fnlwgt
  - capital-gain
  - capital-loss
  - educational-num


numerical_columns:
  - age
  - hours-per-week

categorical_columns:
  - workclass
  - education
  - marital-status
  - occupation
  - relationship
  - race
  - gender
  - native-country


target_column:
  - income
